/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 public/models/the_bulb.glb 
Author: rlaine (https://sketchfab.com/rlaine)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/the-bulb-cdfd1fc6e9da4c5f894cda3c5eb3955d
Title: The Bulb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Bulb_model(props) {
  const { nodes, materials } = useGLTF('./models/the_bulb.glb');
  let scale=10;
  let position=[-2,0,2];
  return (
    <group {...props} dispose={null}>
      <group scale={[scale,scale,scale]} position={position}>
          <group >
            <mesh geometry={nodes.Object_4.geometry} material={materials.Rough_Metal} />
            <mesh geometry={nodes.Object_5.geometry} material={materials.Glass} />
            <mesh geometry={nodes.Object_6.geometry} material={materials.Smooth_Metal} />
            <mesh geometry={nodes.Object_7.geometry} material={materials.Smooth_Metal} />
            <mesh geometry={nodes.Object_8.geometry} material={materials.Light}/>
          </group>
      </group>
    </group>
  )
}

useGLTF.preload('./models/the_bulb.glb')
