/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 public/models/edison_light_bulb.glb 
Author: Fishboe (https://sketchfab.com/ministephen)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/edison-light-bulb-aeb0e4832f04463280510e550e2cdbd5
Title: Edison Light Bulb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Mid_section_model(props) {
  const { nodes, materials } = useGLTF('./models/edison_light_bulb.glb')
  let scale = 0.5;
  let position=[-1,-1.5,0];
  return (
    <group {...props} dispose={null} scale={[scale, scale, scale]} position={position}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.black} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.glass} />
        <mesh geometry={nodes.Object_4.geometry} material={materials['glass-thicker']} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.glow} />
        <mesh geometry={nodes.Object_6.geometry} material={materials.gold} />
        <mesh geometry={nodes.Object_7.geometry} material={materials.metal} />
      </group>
    </group>
  )
}

useGLTF.preload('./models/edison_light_bulb.glb')
