/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 public/models/TV.glb 
Author: Liberi Arcano (https://sketchfab.com/LiberiArcano)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/3december-2021-day-16-tv-time-c8ca01f1ab5c42728480328d02b0b2f9
Title: 3December 2021 Day 16: TV Time
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Second_section_model(props) {
  const { nodes, materials } = useGLTF('./models/TV.glb')
  const scale= 150;
  const position =[0,-2.5,0];
  return (
    <group {...props} dispose={null} scale={[scale,scale,scale]} position={position}>
      <group scale={0.01}>
        <group rotation={[-Math.PI / 2, 0, 0]} >
          <mesh geometry={nodes.Cylinder_Metal_0.geometry} material={materials.Metal} />
          <mesh geometry={nodes.Cylinder_TV_Base_0.geometry} material={materials.TV_Base} />
          <mesh geometry={nodes.Cylinder_TV_ScreenBorder_0.geometry} material={materials.TV_ScreenBorder} />
          <mesh geometry={nodes.Cylinder_Entries_0.geometry} material={materials.Entries} />
          <mesh geometry={nodes.Cylinder_Buttons_0.geometry} material={materials.Buttons} />
          <mesh geometry={nodes.Cylinder_Screen_0.geometry} material={materials.Screen} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('./models/TV.glb')
