/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 ./public/models/wooden_gate.glb 
Author: Asia Matusik (https://sketchfab.com/asiam)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/wooden-gate-7012f137bab14f93aa12bd33f18c5cb6
Title: Wooden gate
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function WoodenGate(props) {
  const { nodes, materials } = useGLTF('./models/wooden_gate.glb')
  const position= [0,-2,0];
  return (
    <group {...props} dispose={null} position={position}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.material_0} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.material_0} />
      </group>
    </group>
  )
}

useGLTF.preload('./models/wooden_gate.glb')
